### ISSUE TITLE
GitHub release ordering issues when i > 10

### ISSUE THREAD

**Issue by gabe-mercury** [amitsingh-007/next-release-tag#101]
When `i` > 10 then the releases that begin with 1 or ordered below releases 2, 3, 4, etc. This is confusing as the latest release is halfway down the release page.

Can we have `i` include a leading 0 when it is less than 10?

**Comment by amitsingh-007** [comment]
Hi @gabe-mercury , thanks for bringing this to light.
Can you shed more light on the issue like what template are you using so that I can reproduce this issue

**Comment by gabe-mercury** [comment]
Sure!

Here is the step in our pipeline:

```
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@517026fab18fd5d384fe0d7c5c2d3ffe2d155f40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
```

Ideally, if `i` is less than 10 it should be padded with a leading zero so the releases show up in the right order.
