### ISSUE TITLE
Error: Old release tag 

### ISSUE THREAD

**Issue by savya10** [amitsingh-007/next-release-tag#27]
Hi,

I'm having an issue with generating a release tag for my package using v4.0.0 - the error message says `Error: Old release tag not found`.  This error also persists after an initial manual release of my package (release tag is v1.0.0), so the solution to Issue #8 doesn't fix it. 

This is the relevant part of my workflow at the moment:

```
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yy.mm.i'
```

I'd greatly appreciate any help you could provide - thanks in advance!
