### ISSUE TITLE
Previous Release Tag Stuck at certain date

### ISSUE THREAD

**Issue by mcquenji** [amitsingh-007/next-release-tag#86]
Somehow the action ignores any release since the 28th of February. Before that it was working perfectly fine...

The logs:

![image](https://github.com/amitsingh-007/next-release-tag/assets/60017181/51660f4f-01ac-42e8-a236-5035298e5ed7)

***Note: These logs pertain to the second instance of the workflow being triggered today***

Although there were multiple releases since then...

![image](https://github.com/amitsingh-007/next-release-tag/assets/60017181/9f25676c-284e-4040-94d8-7ce6863b7190)

**Comment by amitsingh-007** [comment]
Hi @mcquenji , thanks for raising this issue.
Can you confirm if these tags after Feb are part of draft/pre-release or regular release. I checked the same action working fine on my repositories. Although I suspect the action is not able to fetch tags after Feb for your repo for some reason.

**Comment by mcquenji** [comment]
The releases are a regular release. 

However, we've discovered that the action stops working every time a month passes (since 2024) im not quite sure what may cause this issue. We've observed that the action always thinks the latest release is from the last month even when there are new ones. Deleting all releases but the latest one from the current month fixes this issue (until the next month).

**Comment by amitsingh-007** [comment]
That's strange and not happening in my repos.
Is your repository public so that I can take a look? If not, then can you post how you are using this action?

**Comment by mcquenji** [comment]
My repo is private but here's the workflow:

```yaml

name: Create Release

on:
  push:
    branches:
      - main

jobs:
    build:
        uses: ./.github/workflows/build.yaml
        secrets: inherit
    release:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            
            - name: Getting pdf from build action
              uses: actions/download-artifact@v4
              with:
                name: mainpdf-${{ github.sha }}


            - name: Auto Generate Next Release Tag
              uses: amitsingh-007/next-release-tag@v5.1.0
              id: tag
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                tag_prefix: ''
                tag_template: dd.mm.yy.i
            
            - name: Rename PDF
              run: mv main.pdf "LB Planner Thesis v${{ steps.tag.outputs.next_release_tag }}.pdf"
            
            
            - name: Create Release
              id: create_release
              uses: ncipollo/release-action@v1.14.0
              with:
                name: PDF Build ${{ steps.tag.outputs.next_release_tag }}
                tag: ${{ steps.tag.outputs.next_release_tag }}
                artifacts: "LB Planner Thesis v${{ steps.tag.outputs.next_release_tag }}.pdf"
```
